path:
  predictor_5_point_model: model_engine/shape_predictor_5_face_landmarks.dat
  predictor_68_point_model: model_engine/shape_predictor_68_face_landmarks.dat
  cnn_face_detector_model: model_engine/mmod_human_face_detector.dat
  resnet_path: model_engine/dlib_face_recognition_resnet_model_v1.dat
  azure_connection_path: communicate_server/connection
  voice_assis_path: model_engine/assistant_model/voice.mp3
  map_dep_table_path: model_engine/assistant_model/map_department_id.yaml
  decision_tree_model_predict_dep_path: model_engine/assistant_model/decision_tree
  dict_part_body_problems_predict_dep_path: model_engine/assistant_model/dict_data

azure:
  eventhub_name: receivemsg
  eventhub_connection: Endpoint=sb://thesisehealthcare.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=AUeMD+PSZx675wFA4kPllGfSnMwhATPOGPPDWex5jSU=
  iothub_connection: HostName=thesisehealthcare.azure-devices.net;SharedAccessKeyName=serviceAndRegistryRead;SharedAccessKey=mqDNZkuK8UnoS9ccbb3bGm2OI1VCKHRfbODo6BKlfb4=

preprocessing:
  image_size: 150
  base_brightness: 180

identifying_face:
  cycle_count_face_period: 1
  # number_deteced_face_allowed: 3
  number_deteced_face_allowed: 12
  max_edge: 150
  # MAX length for face Detector
  max_length_img: 100
  max_length_img_new_user: 150
  face_detector_model: hog
  shape_predictor_model: 68

camera:
  # Display image
  camera_display_width: 960
  camera_display_height: 540
  # 1920x1080, 30 fps
  camera_mode_1080: 2
  # 1280x720, 60 fps
  camera_mode_720: 3

gui:
  # Width and height for patient face when recognizing
  location_recognize_face_width: 520
  location_recognize_face_height: 510
  # Width and height for patient face when create new user
  location_add_face_width: 730
  location_add_face_height: 480

  # Parameters for GUI
  width_gui: 800
  height_gui: 480
  cam_exam_layout_width: 370
  cam_exam_layout_height: 360
  sensor_exam_layout_width: 400
  sensor_exam_layout_height: 360

timer:
  times_missing_face: 3
  timeout_missing_face: 10

  timeout_validate: 5
  opt_timer_validate: 0

  timeout_get_examination_room: 5
  opt_timer_get_examination_room: 1

  timeout_submit_examination: 5
  opt_timer_submit_examination: 2