path:
  predictor_5_point_model: model_engine/shape_predictor_5_face_landmarks.dat
  predictor_68_point_model: model_engine/shape_predictor_68_face_landmarks.dat
  cnn_face_detector_model: model_engine/mmod_human_face_detector.dat
  resnet_path: model_engine/dlib_face_recognition_resnet_model_v1.dat
  azure_connection_path: communicate_server/connection
  voice_assis_path: model_engine/assistant_model/voice.mp3
  map_dep_table_path: model_engine/assistant_model/map_department_id.yaml
  decision_tree_model_predict_dep_path: model_engine/assistant_model/decision_tree
  dict_part_body_problems_predict_dep_path: model_engine/assistant_model/dict_data
  main_gui_path: gui/form.ui
  measure_sensor_gui_path: gui/progressbar.ui
  okdialog_path: gui/okpopup.ui
  yes_no_dialog: gui/dialog.ui
  momo_gui_dialog: gui/momo_chatbot_gui.ui
  center_face_model: model_engine/centerface_224_128.trt

azure:
  partition_id: 0
  eventhub_name: receivemsg
  eventhub_connection: Endpoint=sb://thesisehealthcare.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=AUeMD+PSZx675wFA4kPllGfSnMwhATPOGPPDWex5jSU=
  iothub_connection: HostName=thesisehealthcare.azure-devices.net;SharedAccessKeyName=serviceAndRegistryRead;SharedAccessKey=mqDNZkuK8UnoS9ccbb3bGm2OI1VCKHRfbODo6BKlfb4=

preprocessing:
  identified_image_size: 150
  base_brightness: 180

identifying_face:
  cycle_count_face_period: 1
  # number_deteced_face_allowed: 100
  number_deteced_face_allowed: 12
  min_edge_detected_face: 150
  # MAX length for face Detector
  max_length_img: 80
  max_length_img_new_user: 150
  # face_detector_model: cnn
  # face_detector_model: hog
  shape_predictor_model: 68

  width_img_center_face: 224
  height_img_center_face: 128 

camera:
  # Capture image
  camera_capture_width: 1280
  camera_capture_height: 720
  flip_method: 0

sensor:
  base_height_sensor: 2.63
  additional_temp_sensor: 1.5

gui:
  # Width and height for patient face when recognizing
  location_recognize_face_width: 975
  location_recognize_face_height: 720

  # Width and height for patient face when create new user
  location_add_face_width: 1280
  location_add_face_height: 720

  margin_face_location: 30

  # # Parameters for GUI
  # width_gui: 800
  # height_gui: 480
  # cam_exam_layout_width: 370
  # cam_exam_layout_height: 360
  # sensor_exam_layout_width: 400
  # sensor_exam_layout_height: 360

timer:
  num_missing_face: 3
  timeout_missing_face: 10

  timeout_validate: 10
  opt_timer_validate: 0

  timeout_get_examination_room: 10
  opt_timer_get_examination_room: 1

  timeout_submit_examination: 10
  opt_timer_submit_examination: 2

  timeout_send_voice_message: 10
  opt_timer_send_voice_message: 3

  timeout_get_init_parameters: 10
  opt_timer_get_init_parameters: 4

momo_message:
  ask_confirm: Momo chào bạn, vui lòng xác nhận thông tin của mình
  ask_new_patient: Bạn đến khám lần đầu phải không, nếu đúng momo giúp bạn đăng ký nhé
  say_bye: Bài bai.
  
  # MESSAGE STATE MEASURE SENSOR AND CHOOSE DEP

  # MESSAGE CHOOSE DEPARTMENT
  ask_choose_dep_frame: Bấm vào nút danh sách khoa
  ask_choose_dep_frame_again: Bạn chưa chọn khoa khám bệnh, vui lòng bấm vào nút danh sách khoa đẻ chọn khoa khám.
  ask_choose_dep: Chọn khoa mình muốn khám, nếu bạn chưa biết khám khoa gì, chọn chuẩn đoán.
  ask_confirm_selected_dep: bấm nút xác nhận để hoàn tất chọn khoa

  # MESSAGE GUIDE MEASURING SENSOR
  ask_measure_sensor: Chọn vào đo chỉ số để đo thông tin sinh học.
  ask_measure_sensor_again: bạn chưa có chỉ số sinh học, vui lòng chọn vào đo chỉ số để lấy thông tin.
  measure_sensor_inform_0: đeo thiết bị đo vào ngón tay. bấm nút i o trên thiết bị và kết nối thiết bị trên màn hình.
  measure_sensor_inform_1: bấm nút s p o 2 trên máy đo và và đợi thông báo đã xong từ momo
  measure_sensor_inform_2: tháo gỡ thiết bị đo ra, đứng lên cân và đợi thông báo đã xong từ momo
  ask_turn_on_oso2: Vui lòng đeo thiết bị đo vào ngón tay và bấm nút i o trên thiết bị.
  confirm_connect_device_success: kết nối với thiết bị rồi, Vui lòng đeo thiết bị đo vào ngón tay và bấm nút s p o 2 trên máy đo và và đợi thông báo đã xong từ momo
  confirm_connected_device: Bạn đã kết nối với thiết bị rồi, Vui lòng đeo thiết bị đo vào ngón tay và bấm nút s p o 2 trên máy đo và và đợi thông báo đã xong từ momo
  
  # MEASURE ESP AND OSO2
  ask_finish_esp_measurement: hoàn tất, đeo thiết bị đo vào ngón tay và bấm nút i o trên thiết bị. bấm nút kết nối thiết bị trên màn hình và s p o 2 trên máy đo và và đợi thông báo đã xong từ momo
  ask_finish_oso2_measurement: hoàn tất, tháo gỡ thiết bị đo ra, đứng lên cân và đợi thông báo đã xong từ momo

  # MESSAGE SUBMIT
  ask_submit_exam: hoàn thành, nhấn vào nút hoàn tất trên màn hình để lấy số thứ tự và số phòng

  # inform_oso2: Để biết cách đo sensor, hãy bấm nút hướng dẫn bên phải phía trên màn hình.
  ask_take_of_mask: Vui lòng cởi khẩu trang để xác thực
  ask_confirm_sensor_infor: Vui lòng xác nhận thông tin

  

  capture_img:
    - nhìn thẳng
    - nhìn lên
    - nhìn xuống
    - quay trái
    - quay phải
    - hoàn tất


