path:
  predictor_5_point_model: model_engine/shape_predictor_5_face_landmarks.dat
  predictor_68_point_model: model_engine/shape_predictor_68_face_landmarks.dat
  cnn_face_detector_model: model_engine/mmod_human_face_detector.dat
  resnet_path: model_engine/dlib_face_recognition_resnet_model_v1.dat
  azure_connection_path: communicate_server/connection
  voice_assis_path: model_engine/assistant_model/voice.mp3
  map_dep_table_path: model_engine/assistant_model/map_department_id.yaml
  decision_tree_model_predict_dep_path: model_engine/assistant_model/decision_tree
  dict_part_body_problems_predict_dep_path: model_engine/assistant_model/dict_data
  main_gui_path: gui/form.ui
  measure_sensor_gui_path: gui/progressbar.ui
  okdialog_path: gui/okpopup.ui
  yes_no_dialog: gui/dialog.ui
  momo_gui_dialog: gui/momo_chatbot_gui.ui

azure:
  eventhub_name: receivemsg
  eventhub_connection: Endpoint=sb://thesisehealthcare.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=AUeMD+PSZx675wFA4kPllGfSnMwhATPOGPPDWex5jSU=
  iothub_connection: HostName=thesisehealthcare.azure-devices.net;SharedAccessKeyName=serviceAndRegistryRead;SharedAccessKey=mqDNZkuK8UnoS9ccbb3bGm2OI1VCKHRfbODo6BKlfb4=

preprocessing:
  image_size: 150
  base_brightness: 180

identifying_face:
  cycle_count_face_period: 1
  # number_deteced_face_allowed: 100
  number_deteced_face_allowed: 12
  max_edge: 150
  # MAX length for face Detector
  max_length_img: 100
  max_length_img_new_user: 150
  # face_detector_model: hog
  face_detector_model: hog
  shape_predictor_model: 68

camera:
  # Capture image
  camera_capture_width: 1920
  camera_capture_height: 1080
  # 1920x1080, 30 fps
  camera_mode_1080: 2
  # 1280x720, 60 fps
  camera_mode_720: 3
  flip_method: 0

gui:
  # Width and height for patient face when recognizing
  location_recognize_face_width: 890
  location_recognize_face_height: 930

  # Width and height for patient face when create new user
  location_add_face_width: 1450
  location_add_face_height: 910

  # Parameters for GUI
  width_gui: 800
  height_gui: 480
  cam_exam_layout_width: 370
  cam_exam_layout_height: 360
  sensor_exam_layout_width: 400
  sensor_exam_layout_height: 360

timer:
  num_missing_face: 3
  timeout_missing_face: 10

  timeout_validate: 10
  opt_timer_validate: 0

  timeout_get_examination_room: 10
  opt_timer_get_examination_room: 1

  timeout_submit_examination: 10
  opt_timer_submit_examination: 2

  timeout_send_voice_message: 10
  opt_timer_send_voice_message: 3

  timeout_get_init_parameters: 10
  opt_timer_get_init_parameters: 4

momo_message:
  ask_confirm: Momo chào bạn, vui lòng xác nhận thông tin của mình ạ
  ask_new_patient: Bạn đến khám lần đầu phải không, nếu đúng momo giúp bạn đăng ký nhé
  say_bye: Bài bai.
  inform_state_3: Bấm vào nút danh sách khoa để chọn khoa mình muốn khám. Sau đó bấm vào đo chỉ số để lấy thông tin sensor.
  inform_oso2: Để biết cách đo sensor, hãy bấm nút hướng dẫn bên phải phía trên màn hình.

  measure_sensor_inform_0: đeo thiết bị đo vào ngón tay và bấm nút i o trên thiết bị.
  measure_sensor_inform_1: bấm nút kết nối thiết bị trên màn hình và s p o 2 trên máy đo và đợi đến khi có thông báo đo xong.
  measure_sensor_inform_2: tháo gỡ thiết bị đo ra, đứng lên cân và đợi thông báo đã xong từ momo

  capture_img:
    - nhìn thẳng
    - nhìn lên
    - nhìn xuống
    - quay trái
    - quay phải
    - hoàn tất


